### PR TITLE
Validates context for activity.

### PR DESCRIPTION
**Pull request by ryasmi**
Would cause problems for https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/docs/examples/AssignmentGraded.json

### CODE REVIEW

**Comment by ryasmi** [comment]
Any idea why this restriction is required @garemoko?

**Comment by garemoko** [comment]
@ryansmith94 there's no technical requirement disallowing statements from containing those properties with other objects and the LRS shouldn't reject them, but i can't think of a use case where those properties make sense where the object is an agent, statement reference or substatement. 

Possibly if the object is an agent representing a robot or clone, then revision and even platform might make sense.

**Comment by garemoko** [comment]
Luke Skywalker reprogrammed R2D2, platform R2, revision D2.

**Comment by ryasmi** [comment]
@garemoko the spec states:

> The revision property MUST only be used if the Statement's Object is an Activity.
> The platform property MUST only be used if the Statement's Object is an Activity.

**Comment by garemoko** [comment]
@ryansmith94 ha. Good catch. No robot agents then.

**Comment by ryasmi** [comment]
Ok thanks @garemoko, I'll get this merged then.

**Pull request merged**
