### PR TITLE
The String class is not suported in PHP 7.

### PR DESCRIPTION
**Pull request by oscarruesga**
Refactor String Class to Str Class to prevent conflict with reserve keys in PHP 7

### CODE REVIEW

**Comment by ryasmi** [comment]
Nice catch @oscarruesga, I'll try to check this out next week, thanks for taking the time to make the fix 👍

**Comment by ryasmi** [comment]
Does "String" actually conflict with any reserved words in PHP 7? I thought it was "string" (with a lowercase "s") that they reserved not "String".

**Comment by oscarruesga** [comment]
But if you use PHP 7 obtain this:

> Fatal error: Cannot use 'String' as class name as it is reserved in /usr/share/nginx/html/vendor/learninglocker/statementfactory/src/String.php on line 3

Here is my php configuration:

image

**Comment by ryasmi** [comment]
Ok thanks for the additional info @oscarruesga. I think it'll be ok to merge this soon, I'll have to do some testing locally, unfortunately we don't have great test coverage in this repo.

**Comment by ryasmi** [comment]
Just merged and added this to the latest release of this library, thanks for your time @oscarruesga and sorry this took so long to get merged.

**Pull request merged**
